language: ruby
script: 'ci/travis.rb'
before_install:
  - travis_retry gem install bundler
  - "rvm current | grep 'jruby' && export AR_JDBC=true || echo"
rvm:
  - 2.0.0
env:
  global:
    - JRUBY_OPTS='-J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Djruby.compile.mode=OFF -J-Djruby.compile.invokedynamic=false -J-Xmx1024M'
  matrix:
    - "GEM=ar:mysql2"
matrix:
  allow_failures:
    - rvm: 1.9.3
      env: "GEM=ar:mysql"
    - rvm: rbx-2
    - rvm: jruby
    - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
bundler_args: --path vendor/bundle --without test
services:
  - memcached
